version = 0.1
[prd-non-tf-905234897161]
[prd-non-tf-905234897161.deploy]
[prd-non-tf-905234897161.deploy.parameters]
stack_name = "test-sam-prj-addressnet"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-51jkkc01hmov"
s3_prefix = "test-sam-prj-addressnet"
region = "us-east-1"
profile = "prd-non-tf-905234897161"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=905234897161.dkr.ecr.us-east-1.amazonaws.com/test-sam-prj-addressnet"]
