AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
# https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    ReservedConcurrentExecutions: 20
#    Environment:
#      Variables:
#        TABLE_NAME: data-table

Resources:
  InferenceApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: address-api.infocruncher.com
      ValidationMethod: DNS

  InferenceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Inference Api Gateway
      StageName: Prod
      TracingEnabled: true
      # EndpointConfiguration: REGIONAL
      Cors:  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        # AllowCredentials: true
      Domain:
        DomainName: address-api.infocruncher.com
        CertificateArn: !Ref InferenceApiCertificate
        Route53:
          HostedZoneName: "infocruncher.com."
      Tags:
        App: AddressPrediction

  InferenceFunction:
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        Inference:
          # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html
          # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Type: Api
          Properties:
            RestApiId: !Ref InferenceApi
            Path: /predict
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.7-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InferenceApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Inference function"
    Value: !Sub "https://${InferenceApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  InferenceApiId:
    Description: 'API Gateway ARN for InferenceApi'
    Value: !Ref InferenceApi
  BasicAWSApiGatewayRootResourceId:
    Description: 'API Gateway RootResourceId for InferenceApi'
    Value: !GetAtt InferenceApi.RootResourceId
  InferenceFunction:
    Description: "Inference Lambda Function ARN"
    Value: !GetAtt InferenceFunction.Arn
